### PR TITLE
Updates RESTful template to include best practices

### PR DESCRIPTION
**Pull request by jclausen**
This PR implements some of my own best practices in API design and makes the template more RESTFUL.  Some notes on changes:

- You'll notice the `errorCode` is removed from the Response model. This is due to the fact that ,RESTfully speaking, the HTTP status code should be expressively used for this purpose.  Returning a code in the JSON is superfluous
- I've removed the `error` and `messages` from non-error responses. This allows the common entity/collection API patterns of consumption to be used (e.g. - When you GET an entity, it returns the entity object as a response).  
- I've also added a `reset` arg to the `getDataPacket` method to allow for the clearing of any existing data that may have been marshalled up to that point in the request.  This prevents having to manually wipe the response before returning the error.
- Added a `STATUS` property struct to the BaseHandler to allow for expressive retrieval of common status codes (i.e. `STATUS.NOT_FOUND`, `STATUS.EXPECTATION_FAILED`)
- Added a `METHODS` struct to the BaseHandler to allow for HTTP verb aliases.  This may seem like overkill, but IIS7, for example, disables everything but `GET` and `POST` out of the box.  This allows some flexibility to account for different servers and (probably few to none now) legacy browsers
- I've added some common responses which handle different scenarios.  One contains an argument for a hard stop, which is the `onAuthorizationFailure` method.  I've found that there are times when you still need to be able to hard exit out of the request when a granular permission fails at some point in an action.  This gives a safety net for that, while allowing the method to still use the Response conventions
- Also added is a request throttling method, which allows you to specify a maximum number of requests for a resource

This update will break backward compatibility, from a consumption standpoint, but I believe it's a good upgrade to the template.

### CODE REVIEW

**Comment by lmajano** [comment]
Overall, great additions. Some comments and clarifications needed, but overrall, great concepts.

**Comment by jclausen** [comment]
Good point on the comments.  I'll go back today and check things out to make sure things are completely clear.

**Comment by jclausen** [comment]
@lmajano : this should be ready to go.  I've added some additional documentation and fixed the test responses to reflect the changes.

**Comment by lmajano** [comment]
Merging manually, as I added a few updates and tests.

**Pull request closed without merging**
